### PR TITLE
bhagyashri.java

### PR DESCRIPTION
**Pull request by Bhagyashri2000**
solution for happy-number

### CODE REVIEW

**Comment by NehaTirumalasetti** [comment]
Try to give your files a unique name, if required you can create a new sub folder within the topic folder for your solutions

**Comment by Bhagyashri2000** [comment]
I will take care next time.

**Comment by NehaTirumalasetti** [comment]
There are a few issues with your PRs:

- All files are supposed to be added within a topics problem sub folder   
[countingvalleys.java](https://github.com/loopccoew/loop2019-20sem1/blob/master/countingvalley.java) should be in the [math&logic/CountingValleys](https://github.com/loopccoew/loop2019-20sem1/tree/master/math%26logic/CountingValleys) folder
- All files should be named appropriately, since there are problem sub folders bhagyashri.java works fine, however unique names are preferred   
- You've named a certain subfolder as [problem_statement](https://github.com/loopccoew/loop2019-20sem1/tree/master/math%26logic/problem_statement), name the folder according to the actual problem statement in this case Restaurant
- Don't add unnecessary files --> [.vscode](https://github.com/loopccoew/loop2019-20sem1/tree/master/.vscode)

**Comment by NehaTirumalasetti** [comment]
Avoi

> There are a few issues with your PRs:
> 
> * All files are supposed to be added within a topics problem sub folder
>   [countingvalleys.java](https://github.com/loopccoew/loop2019-20sem1/blob/master/countingvalley.java) should be in the [math&logic/CountingValleys](https://github.com/loopccoew/loop2019-20sem1/tree/master/math%26logic/CountingValleys) folder
> * All files should be named appropriately, since there are problem sub folders bhagyashri.java works fine, however unique names are preferred
> * You've named a certain subfolder as [problem_statement](https://github.com/loopccoew/loop2019-20sem1/tree/master/math%26logic/problem_statement), name the folder according to the actual problem statement in this case Restaurant

Don't add unnecessary files like [.vscode](https://github.com/loopccoew/loop2019-20sem1/tree/master/.vscode)

**Pull request closed without merging**
